const fs = require('fs');
const path = require('path');

function walk(dir, callback) {
  fs.readdirSync(dir).forEach(f => {
    let dirPath = path.join(dir, f);
    if (fs.statSync(dirPath).isDirectory()) {
      if (!['node_modules', '.git', '.next'].includes(f)) {
        walk(dirPath, callback);
      }
    } else {
      callback(dirPath);
    }
  });
}

const replacements = [
  // Fix invalid Tailwind modifiers generated by the previous bulk replacements
  { p: /backdrop-blur-md\/[0-9]+/g, r: 'backdrop-blur-md' },
  { p: /backdrop-blur-[a-z]+\/[0-9]+/g, r: 'backdrop-blur-md' }
];

['app', 'components'].forEach(dir => {
  walk(dir, file => {
    if (file.endsWith('.tsx') || file.endsWith('.ts') || file.endsWith('.css')) {
      let content = fs.readFileSync(file, 'utf8');
      let newContent = content;
      replacements.forEach(rep => {
        newContent = newContent.replace(rep.p, rep.r);
      });
      if (content !== newContent) {
        fs.writeFileSync(file, newContent);
        console.log('Fixed', file);
      }
    }
  });
});
